version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build:
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ${SERVER_SRC_PATH}:/app
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${CLIENT_WEB_BUILD_PATH}:/usr/share/nginx/html
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    depends_on:
      - app
